/**
 * @fileoverview gRPC-Web generated client stub for lavanet.lava.pairing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.14.0
// source: proto/relay.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_relay_pb from '../proto/relay_pb';


export class RelayerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRelay = new grpcWeb.MethodDescriptor(
    '/lavanet.lava.pairing.Relayer/Relay',
    grpcWeb.MethodType.UNARY,
    proto_relay_pb.RelayRequest,
    proto_relay_pb.RelayReply,
    (request: proto_relay_pb.RelayRequest) => {
      return request.serializeBinary();
    },
    proto_relay_pb.RelayReply.deserializeBinary
  );

  relay(
    request: proto_relay_pb.RelayRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_relay_pb.RelayReply>;

  relay(
    request: proto_relay_pb.RelayRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_relay_pb.RelayReply) => void): grpcWeb.ClientReadableStream<proto_relay_pb.RelayReply>;

  relay(
    request: proto_relay_pb.RelayRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_relay_pb.RelayReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lavanet.lava.pairing.Relayer/Relay',
        request,
        metadata || {},
        this.methodDescriptorRelay,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lavanet.lava.pairing.Relayer/Relay',
    request,
    metadata || {},
    this.methodDescriptorRelay);
  }

}

