// source: pairing/badges.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var gogoproto_gogo_pb = require('../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var epochstorage_stake_entry_pb = require('../epochstorage/stake_entry_pb.js');
goog.object.extend(proto, epochstorage_stake_entry_pb);
goog.exportSymbol('proto.lavanet.lava.pairing.Badge', null, global);
goog.exportSymbol('proto.lavanet.lava.pairing.GenerateBadgeRequest', null, global);
goog.exportSymbol('proto.lavanet.lava.pairing.GenerateBadgeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lavanet.lava.pairing.Badge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lavanet.lava.pairing.Badge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lavanet.lava.pairing.Badge.displayName = 'proto.lavanet.lava.pairing.Badge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lavanet.lava.pairing.GenerateBadgeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lavanet.lava.pairing.GenerateBadgeRequest.displayName = 'proto.lavanet.lava.pairing.GenerateBadgeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.lavanet.lava.pairing.GenerateBadgeResponse.repeatedFields_, null);
};
goog.inherits(proto.lavanet.lava.pairing.GenerateBadgeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lavanet.lava.pairing.GenerateBadgeResponse.displayName = 'proto.lavanet.lava.pairing.GenerateBadgeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lavanet.lava.pairing.Badge.prototype.toObject = function(opt_includeInstance) {
  return proto.lavanet.lava.pairing.Badge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lavanet.lava.pairing.Badge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.Badge.toObject = function(includeInstance, msg) {
  var f, obj = {
    cuAllocation: jspb.Message.getFieldWithDefault(msg, 1, 0),
    epoch: jspb.Message.getFieldWithDefault(msg, 2, 0),
    address: jspb.Message.getFieldWithDefault(msg, 3, ""),
    lavaChainId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    projectSig: msg.getProjectSig_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lavanet.lava.pairing.Badge}
 */
proto.lavanet.lava.pairing.Badge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lavanet.lava.pairing.Badge;
  return proto.lavanet.lava.pairing.Badge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lavanet.lava.pairing.Badge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lavanet.lava.pairing.Badge}
 */
proto.lavanet.lava.pairing.Badge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCuAllocation(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEpoch(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLavaChainId(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setProjectSig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lavanet.lava.pairing.Badge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lavanet.lava.pairing.Badge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lavanet.lava.pairing.Badge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.Badge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCuAllocation();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getEpoch();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLavaChainId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProjectSig_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional uint64 cu_allocation = 1;
 * @return {number}
 */
proto.lavanet.lava.pairing.Badge.prototype.getCuAllocation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.lavanet.lava.pairing.Badge} returns this
 */
proto.lavanet.lava.pairing.Badge.prototype.setCuAllocation = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 epoch = 2;
 * @return {number}
 */
proto.lavanet.lava.pairing.Badge.prototype.getEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.lavanet.lava.pairing.Badge} returns this
 */
proto.lavanet.lava.pairing.Badge.prototype.setEpoch = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string address = 3;
 * @return {string}
 */
proto.lavanet.lava.pairing.Badge.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.Badge} returns this
 */
proto.lavanet.lava.pairing.Badge.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string lava_chain_id = 4;
 * @return {string}
 */
proto.lavanet.lava.pairing.Badge.prototype.getLavaChainId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.Badge} returns this
 */
proto.lavanet.lava.pairing.Badge.prototype.setLavaChainId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bytes project_sig = 5;
 * @return {!(string|Uint8Array)}
 */
proto.lavanet.lava.pairing.Badge.prototype.getProjectSig = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes project_sig = 5;
 * This is a type-conversion wrapper around `getProjectSig()`
 * @return {string}
 */
proto.lavanet.lava.pairing.Badge.prototype.getProjectSig_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getProjectSig()));
};


/**
 * optional bytes project_sig = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getProjectSig()`
 * @return {!Uint8Array}
 */
proto.lavanet.lava.pairing.Badge.prototype.getProjectSig_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getProjectSig()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.lavanet.lava.pairing.Badge} returns this
 */
proto.lavanet.lava.pairing.Badge.prototype.setProjectSig = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.lavanet.lava.pairing.GenerateBadgeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    badgeAddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    projectId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    specId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeRequest}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lavanet.lava.pairing.GenerateBadgeRequest;
  return proto.lavanet.lava.pairing.GenerateBadgeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeRequest}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBadgeAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpecId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lavanet.lava.pairing.GenerateBadgeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBadgeAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProjectId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSpecId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string badge_address = 1;
 * @return {string}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.getBadgeAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeRequest} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.setBadgeAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string project_id = 2;
 * @return {string}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.getProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeRequest} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.setProjectId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string spec_id = 3;
 * @return {string}
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.getSpecId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeRequest} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeRequest.prototype.setSpecId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.lavanet.lava.pairing.GenerateBadgeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    badge: (f = msg.getBadge()) && proto.lavanet.lava.pairing.Badge.toObject(includeInstance, f),
    pairingListList: jspb.Message.toObjectList(msg.getPairingListList(),
    epochstorage_stake_entry_pb.StakeEntry.toObject, includeInstance),
    badgeSignerAddress: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lavanet.lava.pairing.GenerateBadgeResponse;
  return proto.lavanet.lava.pairing.GenerateBadgeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.lavanet.lava.pairing.Badge;
      reader.readMessage(value,proto.lavanet.lava.pairing.Badge.deserializeBinaryFromReader);
      msg.setBadge(value);
      break;
    case 2:
      var value = new epochstorage_stake_entry_pb.StakeEntry;
      reader.readMessage(value,epochstorage_stake_entry_pb.StakeEntry.deserializeBinaryFromReader);
      msg.addPairingList(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBadgeSignerAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lavanet.lava.pairing.GenerateBadgeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lavanet.lava.pairing.GenerateBadgeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBadge();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.lavanet.lava.pairing.Badge.serializeBinaryToWriter
    );
  }
  f = message.getPairingListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      epochstorage_stake_entry_pb.StakeEntry.serializeBinaryToWriter
    );
  }
  f = message.getBadgeSignerAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Badge badge = 1;
 * @return {?proto.lavanet.lava.pairing.Badge}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.getBadge = function() {
  return /** @type{?proto.lavanet.lava.pairing.Badge} */ (
    jspb.Message.getWrapperField(this, proto.lavanet.lava.pairing.Badge, 1));
};


/**
 * @param {?proto.lavanet.lava.pairing.Badge|undefined} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse} returns this
*/
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.setBadge = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.clearBadge = function() {
  return this.setBadge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.hasBadge = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated lavanet.lava.epochstorage.StakeEntry pairing_list = 2;
 * @return {!Array<!proto.lavanet.lava.epochstorage.StakeEntry>}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.getPairingListList = function() {
  return /** @type{!Array<!proto.lavanet.lava.epochstorage.StakeEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, epochstorage_stake_entry_pb.StakeEntry, 2));
};


/**
 * @param {!Array<!proto.lavanet.lava.epochstorage.StakeEntry>} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse} returns this
*/
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.setPairingListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.lavanet.lava.epochstorage.StakeEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.lavanet.lava.epochstorage.StakeEntry}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.addPairingList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.lavanet.lava.epochstorage.StakeEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.clearPairingListList = function() {
  return this.setPairingListList([]);
};


/**
 * optional string badge_signer_address = 3;
 * @return {string}
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.getBadgeSignerAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lavanet.lava.pairing.GenerateBadgeResponse} returns this
 */
proto.lavanet.lava.pairing.GenerateBadgeResponse.prototype.setBadgeSignerAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.lavanet.lava.pairing);
